# CS412 - Machine Learning
## Homework 1
100+5 pts


## Goal

The goal of this homework is three-fold:

*   **Introduction to Python notebooks**
*   **Machine learning experimental set up**
*   **Decision trees**

## Dataset
**German Credit data**, where credit applicants are rated as Good or Bad, according to whether they have re-paid the credit or not. The dataset consists of:

Train Data: (793 samples X 50 attributes)

Test Data:  (207 samples X 50 attributes)

## Task
Given German Credit data, the task is to train a binary decision tree classifier that is able to predict whether a credit applicant will be rated as good or bad.

##1) Initialize

*   First make a copy of the notebook given to you as a starter.

*   Make sure you choose Connect form upper right.

## 2) Load training dataset
[10pts] As long as student use read_csv() function whether reading the file from google drive or uploading it to google colab and read it, 10 points should be given

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
# Load the Pandas libraries with alias 'pd' 
import pandas as pd 


# Read data from file 'credit_german_train.csv' using read_csv() function
data_train = pd.read_csv('credit-german-train_num.csv')

##3) Understanding the dataset

[2pts each] There can be different variaty of used functions, if the required task is satisfied, 2pts should be given to each

..

In [0]:
# print shape
print('Data Dimensionality: ')
print(data_train.shape)


# print attribute names
print('Attribute Names: ')
print(data_train.columns)



# print first 5 rows in your dataset
print('Head of Data: ')
print(data_train.head) # sample function also can be used

Data Dimensionality:
(793, 50)
Attribute Names:
Index(['id', 'duration', 'credit_amount', 'installment_commitment',
       'residence_since', 'age', 'existing_credits', 'num_dependents', 'label',
       'f_worker', 'checking_status_<0', 'checking_status_>=200',
       'checking_status_no checking',
       'credit_history_critical/other existing credit',
       'credit_history_delayed previously', 'credit_history_existing paid',
       'credit_history_no credits/all paid', 'purpose_domestic appliance',
       'purpose_education', 'purpose_furniture/equipment', 'purpose_new car',
       'purpose_other', 'purpose_radio/tv', 'purpose_repairs',
       'purpose_retraining', 'purpose_used car', 'savings_status_500<=X<1000',
       'savings_status_<100', 'savings_status_>=1000',
       'savings_status_no known savings', 'employment_4<=X<7', 'employment_<1',
       'employment_>=7', 'employment_unemployed',
       'personal_status_male div/sep', 'personal_status_male mar/wid',
       'personal_status_male single', 'other_parties_guarantor',
       'other_parties_none', 'property_magnitude_life insurance',
       'property_magnitude_no known property',
       'property_magnitude_real estate', 'other_payment_plans_none',
       'other_payment_plans_stores', 'housing_own', 'housing_rent',
       'job_skilled', 'job_unemp/unskilled non res', 'job_unskilled resident',
       'own_telephone_yes'],
      dtype='object')
Head of Data:
<bound method NDFrame.head of       id  duration  credit_amount  installment_commitment  residence_since  \
0      1         6           1169                       4                4
1      2        48           5951                       2                2
2      3        12           2096                       2                3
3      4        42           7882                       2                4
4      5        24           4870                       3                4
5      6        36           9055                       2                4
6      7        24           2835                       3                4
7      8        36           6948                       2                2
8      9        12           3059                       2                4
9     10        30           5234                       4                2
10    11        12           1295                       3                1
11    12        48           4308                       3                4
12    13        12           1567                       1                1
13    14        24           1199                       4                4
14    15        15           1403                       2                4
15    16        24           1282                       4                2
16    17        24           2424                       4                4
17    18        30           8072                       2                3
18    19        24          12579                       4                2
19    20        24           3430                       3                2
20    21         9           2134                       4                4
21    22         6           2647                       2                3
22    23        10           2241                       1                3
23    24        12           1804                       3                4
24    25        10           2069                       2                1
25    26         6           1374                       1                2
26    27         6            426                       4                4
27    28        12            409                       3                3
28    29         7           2415                       3                2
29    30        60           6836                       3                4
..   ...       ...            ...                     ...              ...
763  764        21          12680                       4                4
764  765        24           2463                       4                3
765  766        12           1155                       3                3
766  767        30           3108                       2                4
767  768        10           2901                       1                4
768  769        12           3617                       1                4
769  770        12           1655                       2                4
770  771        24           2812                       2                4
771  772        36           8065                       3                2
772  773        21           3275                       1                4
773  774        24           2223                       4                4
774  775        12           1480                       2                4
775  776        24           1371                       4                4
776  777        36           3535                       4                4
777  778        18           3509                       4                1
778  779        36           5711                       4                2
779  780        18           3872                       2                4
780  781        39           4933                       2                2
781  782        24           1940                       4                4
782  783        12           1410                       2                2
783  784        12            836                       4                2
784  785        20           6468                       1                4
785  786        18           1941                       4                2
786  787        22           2675                       3                4
787  788        48           2751                       4                3
788  789        48           6224                       4                4
789  790        40           5998                       4                3
790  791        21           1188                       2                4
791  792        24           6313                       3                4
792  793         6           1221                       1                2

     age  existing_credits  num_dependents  label  f_worker  \
0     67                 2               1      1         1
1     22                 1               1      0         1
2     49                 1               2      1         1
3     45                 1               2      1         1
4     53                 2               2      0         1
5     35                 1               2      1         1
6     53                 1               1      1         1
7     35                 1               1      1         1
8     61                 1               1      1         1
9     28                 2               1      0         1
10    25                 1               1      0         1
11    24                 1               1      0         1
12    22                 1               1      1         1
13    60                 2               1      0         1
14    28                 1               1      1         1
15    32                 1               1      0         1
16    53                 2               1      1         1
17    25                 3               1      1         1
18    44                 1               1      0         1
19    31                 1               2      1         1
20    48                 3               1      1         1
21    44                 1               2      1         1
22    48                 2               2      1         0
23    44                 1               1      1         1
24    26                 2               1      1         0
25    36                 1               1      1         1
26    39                 1               1      1         1
27    42                 2               1      1         1
28    34                 1               1      1         1
29    63                 2               1      0         1
..   ...               ...             ...    ...       ...
763   30                 1               1      0         1
764   27                 2               1      1         1
765   40                 2               1      1         1
766   31                 1               1      0         1
767   31                 1               1      1         1
768   28                 3               1      1         1
769   63                 2               1      1         1
770   26                 1               1      1         1
771   25                 2               1      0         1
772   36                 1               1      1         1
773   52                 2               1      1         1
774   66                 3               1      1         1
775   25                 1               1      0         1
776   37                 2               1      1         1
777   25                 1               1      1         1
778   38                 2               1      1         1
779   67                 1               1      1         1
780   25                 2               1      0         1
781   60                 1               1      1         1
782   31                 1               1      1         1
783   23                 1               1      0         1
784   60                 1               1      1         1
785   35                 1               1      1         1
786   40                 1               1      1         1
787   38                 2               2      1         1
788   50                 1               1      0         1
789   27                 1               1      0         1
790   39                 1               2      0         1
791   41                 1               2      1         1
792   27                 2               1      1         1

           ...          property_magnitude_no known property  \
0          ...                                             0
1          ...                                             0
2          ...                                             0
3          ...                                             0
4          ...                                             1
5          ...                                             1
6          ...                                             0
7          ...                                             0
8          ...                                             0
9          ...                                             0
10         ...                                             0
11         ...                                             0
12         ...                                             0
13         ...                                             0
14         ...                                             0
15         ...                                             0
16         ...                                             0
17         ...                                             0
18         ...                                             1
19         ...                                             0
20         ...                                             0
21         ...                                             0
22         ...                                             0
23         ...                                             0
24         ...                                             0
25         ...                                             0
26         ...                                             0
27         ...                                             0
28         ...                                             0
29         ...                                             1
..         ...                                           ...
763        ...                                             1
764        ...                                             0
765        ...                                             0
766        ...                                             0
767        ...                                             0
768        ...                                             0
769        ...                                             0
770        ...                                             0
771        ...                                             1
772        ...                                             0
773        ...                                             0
774        ...                                             1
775        ...                                             0
776        ...                                             0
777        ...                                             0
778        ...                                             0
779        ...                                             0
780        ...                                             0
781        ...                                             0
782        ...                                             0
783        ...                                             0
784        ...                                             0
785        ...                                             0
786        ...                                             0
787        ...                                             0
788        ...                                             1
789        ...                                             1
790        ...                                             0
791        ...                                             0
792        ...                                             0

     property_magnitude_real estate  other_payment_plans_none  \
0                                 1                         1
1                                 1                         1
2                                 1                         1
3                                 0                         1
4                                 0                         1
5                                 0                         1
6                                 0                         1
7                                 0                         1
8                                 1                         1
9                                 0                         1
10                                0                         1
11                                0                         1
12                                0                         1
13                                0                         1
14                                0                         1
15                                0                         1
16                                0                         1
17                                0                         0
18                                0                         1
19                                0                         1
20                                0                         1
21                                1                         1
22                                1                         1
23                                0                         1
24                                0                         1
25                                1                         0
26                                0                         1
27                                1                         1
28                                1                         1
29                                0                         1
..                              ...                       ...
763                               0                         1
764                               0                         1
765                               1                         0
766                               0                         1
767                               1                         1
768                               0                         1
769                               1                         1
770                               1                         1
771                               0                         1
772                               0                         1
773                               0                         0
774                               0                         0
775                               1                         1
776                               0                         1
777                               1                         1
778                               0                         1
779                               0                         1
780                               1                         1
781                               1                         1
782                               1                         1
783                               0                         0
784                               1                         1
785                               0                         1
786                               0                         1
787                               0                         1
788                               0                         1
789                               0                         0
790                               0                         1
791                               0                         1
792                               0                         1

     other_payment_plans_stores  housing_own  housing_rent  job_skilled  \
0                             0            1             0            1
1                             0            1             0            1
2                             0            1             0            0
3                             0            0             0            1
4                             0            0             0            1
5                             0            0             0            0
6                             0            1             0            1
7                             0            0             1            0
8                             0            1             0            0
9                             0            1             0            0
10                            0            0             1            1
11                            0            0             1            1
12                            0            1             0            1
13                            0            1             0            0
14                            0            0             1            1
15                            0            1             0            0
16                            0            1             0            1
17                            0            1             0            1
18                            0            0             0            0
19                            0            1             0            1
20                            0            1             0            1
21                            0            0             1            1
22                            0            0             1            0
23                            0            1             0            1
24                            0            1             0            1
25                            0            1             0            0
26                            0            1             0            0
27                            0            0             1            1
28                            0            1             0            1
29                            0            1             0            1
..                          ...          ...           ...          ...
763                           0            0             0            0
764                           0            1             0            1

In [0]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 50 columns):
id                                               793 non-null int64
duration                                         793 non-null int64
credit_amount                                    793 non-null int64
installment_commitment                           793 non-null int64
residence_since                                  793 non-null int64
age                                              793 non-null int64
existing_credits                                 793 non-null int64
num_dependents                                   793 non-null int64
label                                            793 non-null int64
f_worker                                         793 non-null int64
checking_status_<0                               793 non-null int64
checking_status_>=200                            793 non-null int64
checking_status_no checking                      793 non-null int64
credit_history_critical/other existing credit    793 non-null int64
credit_history_delayed previously                793 non-null int64
credit_history_existing paid                     793 non-null int64
credit_history_no credits/all paid               793 non-null int64
purpose_domestic appliance                       793 non-null int64
purpose_education                                793 non-null int64
purpose_furniture/equipment                      793 non-null int64
purpose_new car                                  793 non-null int64
purpose_other                                    793 non-null int64
purpose_radio/tv                                 793 non-null int64
purpose_repairs                                  793 non-null int64
purpose_retraining                               793 non-null int64
purpose_used car                                 793 non-null int64
savings_status_500<=X<1000                       793 non-null int64
savings_status_<100                              793 non-null int64
savings_status_>=1000                            793 non-null int64
savings_status_no known savings                  793 non-null int64
employment_4<=X<7                                793 non-null int64
employment_<1                                    793 non-null int64
employment_>=7                                   793 non-null int64
employment_unemployed                            793 non-null int64
personal_status_male div/sep                     793 non-null int64
personal_status_male mar/wid                     793 non-null int64
personal_status_male single                      793 non-null int64
other_parties_guarantor                          793 non-null int64
other_parties_none                               793 non-null int64
property_magnitude_life insurance                793 non-null int64
property_magnitude_no known property             793 non-null int64
property_magnitude_real estate                   793 non-null int64
other_payment_plans_none                         793 non-null int64
other_payment_plans_stores                       793 non-null int64
housing_own                                      793 non-null int64
housing_rent                                     793 non-null int64
job_skilled                                      793 non-null int64
job_unemp/unskilled non res                      793 non-null int64
job_unskilled resident                           793 non-null int64
own_telephone_yes                                793 non-null int64
dtypes: int64(50)
memory usage: 309.8 KB

##4) Shuffle and Split training data to train (80%) and validation (20%) 

[5pts] Shuffle data

[5pts] split data

*Note: Solutions can vary

In [0]:
from sklearn.utils import shuffle

# Shuffle the training data
from sklearn.utils import shuffle
data_train = shuffle(data_train)

# Split 
splt = int(len(data_train)*.8)
split_data_train = data_train[1:splt]
split_data_valid = data_train[splt+1:]

##5) Train DecisionTreeClassifier 

[5pts] split train data to attributes and label

[5pts] split validation data to attribute and label *can be added in the next section*

[5pts] Train tree 1 (using default or specify min_samples_split=1.0) both are correct

[5pts] Train tree 2

[5pts] Train tree 3

In [0]:
# To train Decision Tree you need two variables (1) attributes (2) labels

# Split your training data to "attributes" and "labels" 

tr_lbl  = split_data_train['label']
tr_data = split_data_train.drop('label', axis=1)
val_lbl  = split_data_valid['label']
val_data = split_data_valid.drop('label', axis=1)



# Train Decision tree classifier
from sklearn.tree import DecisionTreeClassifier


dtree1 = DecisionTreeClassifier()
dtree1.fit(tr_data, tr_lbl)

dtree2 = DecisionTreeClassifier(min_samples_split=3)
dtree2.fit(tr_data, tr_lbl)

dtree3 = DecisionTreeClassifier(min_samples_split=5)
dtree3.fit(tr_data, tr_lbl)

## 6) Testing your trained classifier on Validation set

[6pts] predicting validation labels on tree 1 and calculate accuracy using predicted labels and true labels


[6pts] predicting validation labels on tree 2 & calculate accuracy using predicted labels and true labels


[6pts] predicting validation labels on tree 3 & calculate accuracy using predicted labels and true labels

In [0]:
from sklearn.metrics import accuracy_score


pred_val = dtree1.predict(val_data)
print(accuracy_score(val_lbl, pred_val)*100)

pred_val = dtree2.predict(val_data)
print(accuracy_score(val_lbl, pred_val)*100)

pred_val = dtree3.predict(val_data)
print(accuracy_score(val_lbl, pred_val)*100)

70.88607594936708
72.15189873417721
72.15189873417721

## 7) Testing your trained classifier on Test set

[10pts] Reading test data

[5pts] split test data to attributes and label

[6pts] predicting test labels & calculating accuracy on test data

In [0]:
# Load test data
data_test = pd.read_csv("drive/My Drive/ML412_Fall2018_2019/HW1/credit-german-test_num.csv") 


# Predict
te_lbl  = data_test['label']
te_data = data_test.drop('label', axis=1)

pred_te = dtree1.predict(te_data)
accuracy_score(te_lbl, pred_te)*100

70.53140096618358

##8) Summary 

[10pts] Check if the student understand the concept of model selection and splitting the data to train and validation. Give "bol" points basically I just want that a summary is here.

##9) BONUS (5pts) 

Try different pruning or early stopping echniques for decision trees. If you obtain a higher accuracy on your test set, you will receive 5pts bonus.

## Questions? 

You should ask all your Google Colab related questions to Discussions and feel free to answer/share your answer regarding this part (Colab). 

You can also ask/answer about which functions to use and what libraries... 

However you should not ask about the core part, that is what is validation/test, which one shd. have higher performance, what are your scores etc.